<?php

namespace RippleDevs\LaravelFaker\Tests;

use Faker\Generator;
use Orchestra\Testbench\TestCase as Orchestra;
use RippleDevs\LaravelFaker\Providers\LaravelFakerServiceProvider;

abstract class EnglishTestCase extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->useEnglishFaker();
    }
}
